# Generated by Django 3.1.3 on 2020-11-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reus', '0002_auto_20201028_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_event',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
