# Generated by Django 3.1.3 on 2021-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reus', '0004_auto_20210113_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='quadNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_link', models.URLField(max_length=255)),
                ('body', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='quadPrevious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_link', models.URLField(max_length=255)),
                ('body', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
