# Generated by Django 3.1.3 on 2021-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reus', '0005_quadnext_quadprevious'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadnext',
            name='title',
            field=models.TextField(default='w'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprevious',
            name='title',
            field=models.TextField(default='w'),
            preserve_default=False,
        ),
    ]
