# Generated by Django 3.1.3 on 2021-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reus', '0006_auto_20210219_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadnext',
            name='datestr',
            field=models.TextField(default='we'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quadprevious',
            name='datestr',
            field=models.TextField(default='wer'),
            preserve_default=False,
        ),
    ]
